# Generated by Django 4.1.7 on 2023-05-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('projects', '0006_remove_project_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='skills.skill'),
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
