# Generated by Django 4.1.7 on 2023-05-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_likes_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='project',
        ),
    ]
