# Generated by Django 4.1.7 on 2023-05-14 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon', models.CharField(choices=[('github', 'Github'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('twitch', 'Twitch'), ('other', 'Other')], default='other', max_length=15)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_me', to='core.profile')),
            ],
        ),
    ]
