# Generated by Django 4.1.7 on 2023-05-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sociallink_aboutme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='profile',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='about_me', to='core.sociallink'),
        ),
    ]
