# Generated by Django 4.1.7 on 2023-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sociallink_profile_aboutme_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(choices=[('github', 'Github'), ('linkedin', 'Linkedin'), ('instagram', 'Instagram'), ('leetcode', 'Leetcode'), ('other', 'Other')], default='other', max_length=15),
        ),
    ]
