# Generated by Django 4.1.7 on 2023-05-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instution', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('courses', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='education')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
