# Generated by Django 4.1.7 on 2023-05-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='courses',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(null=True, upload_to='education'),
        ),
    ]
